### ISSUE TITLE
Error using check-safety/trace features (AttributeError: 'alias' object has no attribute 'asname')

### ISSUE THREAD

**Issue by wunderwuzzi23** [trailofbits/fickling#21] opened 2022-08-29 03:13 UTC
Hello! Great tool, I like that it also includes a way to check for potentially malicious `opcodes` in pickle files. 

I injected a payload into a stylegan2-ada pickle file and it behaves as expected. :)

Now, when running both `--check-safety` or `--trace` commands the following error is shown:

```
!fickling --check-safety /tmp/network-snapshot-000250.backdoor.pkl
```

```
Traceback (most recent call last):
  File "/usr/local/bin/fickling", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/fickling/cli.py", line 79, in main
    return [1, 0][check_safety(pickled)]
  File "/usr/local/lib/python3.7/dist-packages/fickling/analysis.py", line 38, in check_safety
    shortened, already_reported = shorten_code(node)
  File "/usr/local/lib/python3.7/dist-packages/fickling/analysis.py", line 23, in shorten_code
    code = unparse(ast_node).strip()
  File "/usr/local/lib/python3.7/dist-packages/astunparse/__init__.py", line 13, in unparse
    Unparser(tree, file=v)
  File "/usr/local/lib/python3.7/dist-packages/astunparse/unparser.py", line 38, in __init__
    self.dispatch(tree)
  File "/usr/local/lib/python3.7/dist-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/usr/local/lib/python3.7/dist-packages/astunparse/unparser.py", line 113, in _ImportFrom
    interleave(lambda: self.write(", "), self.dispatch, t.names)
  File "/usr/local/lib/python3.7/dist-packages/astunparse/unparser.py", line 19, in interleave
    f(next(seq))
  File "/usr/local/lib/python3.7/dist-packages/astunparse/unparser.py", line 66, in dispatch
    meth(tree)
  File "/usr/local/lib/python3.7/dist-packages/astunparse/unparser.py", line 856, in _alias
    if t.asname:
AttributeError: 'alias' object has no attribute 'asname'
```

Let me know if there is anything more needed to debug the issue.

Greetings!

**Comment by ESultanik** [comment] 2022-09-07 15:43
This bug was first, but in debugging #22 we discovered that it is a duplicate of that one, which already has a workaround. The workaround will be included in the next release, version 0.0.4. In the mean time, upgrading to Python 3.9 or newer should fix the problem.

**Closed by ESultanik** 2022-09-07 15:43 UTC
Labels: bug, duplicate
